"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { createTheme } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

const darkTheme = createTheme({
  type: "dark",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider theme={darkTheme}>{children} </NextUIProvider>
      </body>
    </html>
  );
}
